### ISSUE TITLE
some problems on the blockly test with Burger

### ISSUE THREAD

**Issue by EndlessLoops** [aravindk2604/turtlebot3_blockly#1]
Hi,

when i carried out the turtlebot3_blockly with a burger ,i found some problems.

it can't execute the other blockly command  except for the first and Burger can't stop when it run the first blockly command .

Additionally,only in the case of the use of python 2, the blockly command can be used.

thanks

**Comment by aravindk2604** [comment]
### Hello,
Would you be able to post a picture of the blocks that you used for your program?
I could not understand what the error is.
--
Aravind

**Comment by EndlessLoops** [comment]
hi，

The burger only execute the first blockly command  even if Even when there are multiple commands，
and burger can't stop when it execute the first blockly command.
