### ISSUE TITLE
Not able to install turtlebot3_blocklt

### ISSUE THREAD

**Issue by sergefc** [aravindk2604/turtlebot3_blockly#2]
After the installation without problem
At the Launch level the line : source devel_isolated/setup.bash 
the setup.bash script is not there.
 I found it with this modification: 
source devel_isolated/turtlebot3_blockly/setup.bash
When I send the command
roslaunch turtlebot3_blockly turtlebot3_blockly.launch
I obtain these errors:
![screenshot at 2018-04-08 14 29 37](https://user-images.githubusercontent.com/17831141/38467561-ab36de58-3b3a-11e8-8122-2bbe2c36a0de.png)

Where is the errors I do ?
I am trying four times the installation with same issue

Best regards
Serge

**Comment by aravindk2604** [comment]
Hi Serge,
I'm unable to figure out what is missing with the info that you have provided.
Can you please reply with the output of the following:

`$ tree -L 3 ~/blockly_ws`

**Comment by sergefc** [comment]
Bonjour,
![screenshot at 2018-04-16 10 12 57](https://user-images.githubusercontent.com/17831141/38797468-d38f1418-415e-11e8-8250-2ae6308b3c6d.png)
Regards

**Comment by aravindk2604** [comment]
I'm not sure why **robot_blockly** is inside your **blockly_ws.**
It should be something like this:

ak@akAW:~/b_ws$ tree -L 3 ~/b_ws
/home/ak/b_ws
├── build_isolated
│   ├── catkin_make_isolated.cache
│   └── turtlebot3_blockly
│       ├── catkin
│       ├── catkin_generated
│       ├── CATKIN_IGNORE
│       ├── cmake
│       ├── CMakeCache.txt
│       ├── CMakeFiles
│       ├── cmake_install.cmake
│       ├── CTestTestfile.cmake
│       ├── gtest
│       ├── install_manifest.txt
│       ├── java
│       ├── Makefile
│       └── test_results
├── devel_isolated
│   └── turtlebot3_blockly
│       ├── env.sh
│       ├── include
│       ├── lib
│       ├── setup.bash
│       ├── setup.sh
│       ├── _setup_util.py
│       ├── setup.zsh
│       └── share
├── install_isolated
│   ├── env.sh
│   ├── include
│   │   └── turtlebot3_blockly
│   ├── lib
│   │   ├── pkgconfig
│   │   ├── python2.7
│   │   └── turtlebot3_blockly
│   ├── setup.bash
│   ├── setup.sh
│   ├── _setup_util.py
│   ├── setup.zsh
│   └── share
│       ├── common-lisp
│       ├── gennodejs
│       ├── roseus
│       └── turtlebot3_blockly
└── src
    └── turtlebot3_blockly
        ├── CMakeLists.txt
        ├── frontend
        ├── graph
        ├── img
        ├── launch
        ├── LICENSE
        ├── package.xml
        ├── README.md
        ├── scripts
        └── srv

34 directories, 21 files

**Comment by aravindk2604** [comment]
Also please install the respective dependencies for ros.

**Comment by sergefc** [comment]
I will reinstall turtlebot3_blockly.

**Comment by sergefc** [comment]
I just reinstall turtlebot3_blockly.
I am using this procedure:

$ mkdir -p ~/blockly_ws/src
$ cd ~/blockly_ws/src
$ git clone https://github.com/dabit-industries/turtlebot3_blockly
$ cd turtlebot3_blockly/frontend/
$ git submodule add https://github.com/dabit-industries/ace-builds.git ace-builds
$ git submodule init
$ git submodule update
$ git submodule add https://github.com/dabit-industries/blockly.git blockly
$ git submodule init
$ git submodule update
$ cd ~/blockly_ws/
$ catkin_make_isolated -j2 --pkg turtlebot3_blockly --install

and I have this error I saw many times :+1: 

raceback (most recent call last):
  File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/gensrv_py.py", line 43, in <module>
    import genpy.generator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    from rocon_python_utils import yaml
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rocon_python_utils/__init__.py", line 22, in <module>
    from . import network
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rocon_python_utils/network/__init__.py", line 9, in <module>
    from .pinger import Pinger
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rocon_python_utils/network/pinger.py", line 18, in <module>
    from rocon_python_comms import WallRate
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rocon_python_comms/__init__.py", line 21, in <module>
    from .connections import Connection, ConnectionCache, ConnectionCacheNode
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rocon_python_comms/connections.py", line 34, in <module>
    import rocon_std_msgs.msg as rocon_std_msgs
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rocon_std_msgs/msg/__init__.py", line 1, in <module>
    from ._Connection import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rocon_std_msgs/msg/_Connection.py", line 9, in <module>
    class Connection(genpy.Message):
AttributeError: 'module' object has no attribute 'Message'
------------------------------------------------------------------------
Below my new directory :
![screenshot at 2018-04-16 15 24 12](https://user-images.githubusercontent.com/17831141/38811910-1fcb7f5c-418b-11e8-8865-b1d0e139c45c.png)

**Comment by wenjun001** [comment]
YES same problem does not work please fix it

**Comment by MyNameIsCosmo** [comment]
`sudo pip2 install pyyaml` 

There should be a *requirements.txt* to install needed python libs for this repo.

Robot Blockly is currently being rewritten using the latest Google Blockly base, so this repo should only be used for research purposes.
